# Generated by Django 3.2.8 on 2021-10-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bludo',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
