# Generated by Django 3.2.8 on 2021-10-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptsite', '0002_auto_20211029_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bludo',
            options={'verbose_name': 'блюдо', 'verbose_name_plural': 'Блюдо'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент для блюда', 'verbose_name_plural': 'Ингредиент'},
        ),
    ]
