# Generated by Django 3.2.8 on 2021-10-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptsite', '0003_auto_20211030_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='bludo',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='receptsite.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
