# Generated by Django 3.2.8 on 2021-11-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptsite', '0004_bludo_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='bludo',
            name='image',
            field=models.CharField(default=2, max_length=500, verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
